version: '3'

services:
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENV=docker
    volumes:
      - .:/app:cached
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app --log-level debug

  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - DOCKERIZED=1
    volumes:
      - .:/app:cached
    command: streamlit run app/main.py --server.port 8501



